### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by KittyGiraudel** [MrDinsdale/Cactus#3]
Hey! Nice work with Cactus, it looks promising. :)

If that is not too much asking, I'd love credits for the few functions you used from me:
- common/helpers/mixins/_linear-gradient.scss
- common/helpers/functions/_is-direction.scss
- common/helpers/functions/_legacy-direction.scss

.. since I believe you took it from [here](https://github.com/thoughtbot/bourbon/issues/520) and [here](http://www.sitepoint.com/building-linear-gradient-mixin-sass). 

Simply adding the following line to code blocks would be enough for me:

``` scss
// @author Hugo Giraudel
```

Thanks. :)

**Comment by MrDinsdale** [comment]
Most definitely, done. Awesome helper, I actually found it in a blog post but can't find the link.
