### ISSUE TITLE
Consider SassDoc comments

### ISSUE THREAD

**Issue by KittyGiraudel** [MrDinsdale/Cactus#4]
You already use some kind of comments to describe a couple of helper functions. Maybe you could consider moving to SassDoc comments to have automatic API documentation for Cactus. :)

**Comment by MrDinsdale** [comment]
Nice, yeah that would be a great move actually. I've never used it before but will try and get it set up as soon as I'm completely happy with the initial set up!

**Comment by MrDinsdale** [comment]
Going to close this until SassDoc allows documentation of classes as well as functions and mixins.
